# Generated by Django 3.1.4 on 2021-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='discipline_name_txt',
            new_name='discipline_name_text',
        ),
    ]
